version: '3.1'

services:
  db:
    image: postgres:13.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_password"
  
  backend:
    build:
      context: ./server
    restart: always
    ports:
      - 80:8000
    links:
      - db
    volumes:
      - ./server/config.json:/app/config.json
    environment:
      GIN_MODE: "release"
 
